from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime, timezone
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
WRITING_DIR = ROOT / "docs" / "writing"
INDEX_FILE = ROOT / "docs" / "writing.md"
NEW_WINDOW_DAYS = 30


@dataclass
class Post:
    title: str
    date: date
    path: Path

    @property
    def rel_link(self) -> str:
        return f"writing/{self.path.name}"

    @property
    def year(self) -> int:
        return self.date.year

    def format_line(self, now: date) -> str:
        is_new = (now - self.date).days <= NEW_WINDOW_DAYS
        badge = " `New`" if is_new else ""
        return f"- [{self.title}]({self.rel_link}) - {self.date.isoformat()}{badge}"


@dataclass
class UpNextPost:
    title: str
    path: Path

    @property
    def rel_link(self) -> str:
        return f"writing/{self.path.name}"

    def format_line(self) -> str:
        return f"- [{self.title}]({self.rel_link}) - `Up next`"


FRONT_MATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n?", re.DOTALL)
DATE_RE = re.compile(r"^date:\s*([0-9]{4}-[0-9]{2}-[0-9]{2})\s*$", re.MULTILINE)
TITLE_RE = re.compile(r"^title:\s*(.+?)\s*$", re.MULTILINE)
H1_RE = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)
UP_NEXT_RE = re.compile(r"^up_next:\s*(true|yes)\s*$", re.MULTILINE | re.IGNORECASE)
STATUS_RE = re.compile(r"^status:\s*up_next\s*$", re.MULTILINE | re.IGNORECASE)


def parse_title(content: str, front_matter: str) -> str | None:
    title_match = TITLE_RE.search(front_matter)
    if title_match:
        return title_match.group(1).strip().strip('"').strip("'")

    h1_match = H1_RE.search(content)
    if h1_match:
        return h1_match.group(1).strip()
    return None


def is_up_next(front_matter: str) -> bool:
    return bool(UP_NEXT_RE.search(front_matter) or STATUS_RE.search(front_matter))


def parse_post(post_path: Path) -> tuple[Post | None, UpNextPost | None]:
    content = post_path.read_text(encoding="utf-8")
    front_matter_match = FRONT_MATTER_RE.match(content)
    if not front_matter_match:
        return None, None

    front_matter = front_matter_match.group(1)
    title = parse_title(content, front_matter)
    if not title:
        return None, None

    if is_up_next(front_matter):
        return None, UpNextPost(title=title, path=post_path)

    date_match = DATE_RE.search(front_matter)
    if not date_match:
        return None, None
    post_date = datetime.strptime(date_match.group(1), "%Y-%m-%d").date()
    return Post(title=title, date=post_date, path=post_path), None


def build_writing_page(posts: list[Post], up_next_posts: list[UpNextPost]) -> str:
    today = datetime.now(timezone.utc).date()
    sorted_posts = sorted(posts, key=lambda p: p.date, reverse=True)
    sorted_up_next = sorted(up_next_posts, key=lambda p: p.title.lower())
    latest = sorted_posts[:5]

    lines: list[str] = [
        "# Writing",
        "",
        "Notes on data systems, AI, engineering leadership, and building real platforms.",
        "",
        "## Latest",
        "",
    ]

    if latest:
        lines.extend(post.format_line(today) for post in latest)
    else:
        lines.append("- No published posts yet.")

    lines.extend(
        [
            "",
            "## Up next",
            "",
        ]
    )

    if sorted_up_next:
        lines.extend(post.format_line() for post in sorted_up_next)
    else:
        lines.append("- No upcoming posts tagged yet.")

    lines.extend(
        [
            "",
            "## Archive",
            "",
        ]
    )

    if sorted_posts:
        years = sorted({post.year for post in sorted_posts}, reverse=True)
        for year in years:
            lines.extend([f"### {year}", ""])
            for post in [p for p in sorted_posts if p.year == year]:
                lines.append(post.format_line(today))
            lines.append("")
    else:
        lines.append("- No archived posts yet.")
        lines.append("")

    lines.extend(
        [
            "> `New` indicates posts published in the last 30 days.",
            "",
            "<!-- This file is generated by scripts/generate_writing_index.py -->",
        ]
    )

    return "\n".join(lines)


def main() -> None:
    posts: list[Post] = []
    up_next_posts: list[UpNextPost] = []
    for path in sorted(WRITING_DIR.glob("*.md")):
        parsed_post, parsed_up_next = parse_post(path)
        if parsed_post is not None:
            posts.append(parsed_post)
        if parsed_up_next is not None:
            up_next_posts.append(parsed_up_next)

    INDEX_FILE.write_text(build_writing_page(posts, up_next_posts), encoding="utf-8")
    print(
        f"Generated {INDEX_FILE} with {len(posts)} published post(s) and "
        f"{len(up_next_posts)} up-next post(s)."
    )


if __name__ == "__main__":
    main()
